-- 1. Create News Table
create table public.news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  body text not null,
  author text default 'Junta de Freguesia'
);

-- 2. Enable RLS
alter table public.news enable row level security;

-- 3. Policies
-- Everyone can read news
create policy "Public can read news" 
on public.news for select 
using ( true );

-- Only authenticated users can insert (Simulating Admin)
-- In a real app, you'd check for a specific email or role.
create policy "Admins can post news" 
on public.news for insert 
to authenticated 
with check ( true );
