-- ============================================
-- 2580 Carregado – Full Schema (Phases 2 & 3)
-- Run ALL of this in your Supabase SQL Editor
-- ============================================

-- ── PHASE 2 ────────────────────────────────

-- 1. Business Directory
create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  category text not null,
  address text,
  phone text,
  description text,
  website text,
  instagram text,
  is_premium boolean default false,
  is_active boolean default true,
  latitude double precision,
  longitude double precision
);
alter table public.businesses enable row level security;
create policy "Public can read active businesses" on public.businesses for select using (is_active = true);
create policy "Admins can manage businesses" on public.businesses for all to authenticated with check (true);

-- 2. Dynamic Ads (Banner carousel)
create table if not exists public.ads (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  description text,
  label text,
  gradient text default 'linear-gradient(135deg, #10B981 0%, #3B82F6 100%)',
  link_url text,
  is_active boolean default true,
  expires_at timestamptz
);
alter table public.ads enable row level security;
create policy "Public can read active ads" on public.ads for select using (is_active = true AND (expires_at is null OR expires_at > now()));
create policy "Admins can manage ads" on public.ads for all to authenticated with check (true);

-- 3. Community Alerts & Scams
create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  type text not null check (type in ('scam', 'safety', 'info', 'urgent')),
  title text not null,
  body text not null,
  location text,
  author text default 'Comunidade',
  is_verified boolean default false,
  is_active boolean default true
);
alter table public.alerts enable row level security;
create policy "Public can read active alerts" on public.alerts for select using (is_active = true);
create policy "Anyone can submit an alert" on public.alerts for insert with check (true);
create policy "Admins can manage alerts" on public.alerts for all to authenticated with check (true);

-- ── PHASE 3 ────────────────────────────────

-- 4. Boleia (Carpooling)
create table if not exists public.boleia (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  origin text not null,
  destination text not null,
  date date not null,
  time time not null,
  seats int default 1 check (seats >= 1 and seats <= 8),
  contact text not null,
  notes text,
  recurring boolean default false
);
alter table public.boleia enable row level security;
create policy "Public can read boleia" on public.boleia for select using (true);
create policy "Anyone can post boleia" on public.boleia for insert with check (true);
create policy "Admins manage boleia" on public.boleia for all to authenticated with check (true);

-- 5. Perdidos & Achados (Lost & Found)
create table if not exists public.perdidos_achados (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  type text not null check (type in ('lost_pet','found_pet','lost_item','found_item','lost_doc','found_doc')),
  title text not null,
  description text not null,
  location text,
  contact text not null,
  reward text,
  resolved boolean default false
);
alter table public.perdidos_achados enable row level security;
create policy "Public can read perdidos" on public.perdidos_achados for select using (true);
create policy "Anyone can post perdidos" on public.perdidos_achados for insert with check (true);
create policy "Admins manage perdidos" on public.perdidos_achados for all to authenticated with check (true);

-- 6. Eventos Locais
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  title text not null,
  type text not null default 'Outro',
  date date not null,
  time time,
  location text,
  description text,
  organizer text,
  is_active boolean default true
);
alter table public.events enable row level security;
create policy "Public can read events" on public.events for select using (is_active = true);
create policy "Anyone can suggest events" on public.events for insert with check (true);
create policy "Admins manage events" on public.events for all to authenticated with check (true);

-- ── SEED DATA (optional demo content) ──────

-- Ads banner seed
insert into public.ads (title, description, label, gradient, link_url) values
  ('Padaria Carregadense', 'Pão fresco todos os dias — Rua Vaz Monteiro, 107', 'Parceiro Local', 'linear-gradient(135deg, #F59E0B 0%, #EF4444 100%)', null),
  ('Oficina Central', 'Revisões e reparações – Preço Justo', 'Serviços Auto', 'linear-gradient(135deg, #3B82F6 0%, #1D4ED8 100%)', null),
  ('Talho do Povo', 'A melhor carne do Carregado', 'Comércio Local', 'linear-gradient(135deg, #10B981 0%, #059669 100%)', null);

-- Business Directory seed
insert into public.businesses (name, category, address, is_premium, is_active) values
  (
    'Padaria Carregadense, Lda.',
    'Padaria',
    'Rua Vaz Monteiro, 107, 2580-505 Carregado',
    true,
    true
  );
