-- 1. Create Housing Listings Table
create table public.housing_listings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text check (type in ('Rent', 'Sale')),
  title text not null,
  price text not null,
  contact text not null,
  description text,
  is_premium boolean default false
);

-- 2. Create Reports Table
create table public.reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  description text not null,
  location text,
  status text default 'Pending'
);

-- 3. Enable Row Level Security (RLS)
alter table public.housing_listings enable row level security;
alter table public.reports enable row level security;

-- 4. Create Policies (Allow Public Read/Write for Demo purposes)
-- In a real production app, you would restrict Writes to authenticated users.

-- Housing: Everyone can read
create policy "Public Listings are viewable by everyone" 
on public.housing_listings for select 
using ( true );

-- Housing: Everyone can insert (Simulating community board)
create policy "Anyone can insert a listing" 
on public.housing_listings for insert 
with check ( true );

-- Reports: Everyone can insert
create policy "Anyone can submit a report" 
on public.reports for insert 
with check ( true );
